#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  target_device=""
  associated_only=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'iw-bssid-scan' \
    'iw-tools'
  _check_cmd \
    "wifi-tethering-status"
  _check_cmd \
    'sudo' \
    'tsu'
}

_dumpsys() {
  local \
    _cmd=()
  _cmd=(
    dumpsys
      wifi
  )
  sudo \
    "${_cmd[@]}"
}

_bssids_get() {
  local \
    _device="${1}" \
    _associated_only="${2}" \
    _bssids=() \
    _iw_bssid_scan_opts=() \
    _tethering
  if [[ "${_associated_only}" == "y" ]]; then
    _iw_bssid_scan_opts+=(
      -a
    )
  fi
  _bssids+=( $( \
    iw-bssid-scan \
      "${_iw_bssid_scan_opts[@]}" \
      "${_device}")
  )
  if [[ "${_bssids[*]}" == "" ]]; then
    _tethering="$( \
      wifi-tethering-status)"
    if [[ "${_tethering}" == "enabled" ]]; then
      _bssids+=( $( \
        _tethering_bssid_get)
      )
    fi
  fi
  echo \
    "${_bssids[@]}"
}

_tethering_bssid_get() {
  local \
    _bsss=() \
    _wifi_tethering_conf_line \
    _bssid \
    _bssid_line \
    _pattern \
    _dumpsys_out
  _pattern="mCurrentSoftApConfiguration: ssid = " 
  _dumpsys_out="$( \
    _dumpsys)"
  _wifi_tethering_conf_line="$( \
    echo \
      "${_dumpsys_out}" | \
      grep \
        -n \
        "${_pattern}" | \
      awk \
        -F \
          ":" \
        '{print $1}')" 
  _bssid_line="$(( \
    "${_wifi_tethering_conf_line}" + \
    1))"
  _bssid="$( \
    echo \
      "${_dumpsys_out}" | \
      head \
        -n \
        "${_bssid_line}" | \
        tail \
          -n \
          1 | \
          awk \
            '{print $3}')"
  _bsss=(
    "${_bssid}"
  )
  echo \
    "${_bsss[*]}"
}

_android_bssid_scan() {
  local \
    _device="${1}" \
    _associated_only="${2}" \
    _cmd=()
 _bssids=( $( \
   _bssids_get \
    "${_device}" \
    "${_associated_only}")
  )
  echo \
    "${_bssids[@]}"
}

_set_overrides() {
  _set_override \
    "target" \
    "device" \
    "wlan0"
  _set_override \
    "associated" \
    "only" \
    "n"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Returns visible BSSIDs

Usage:
  $(_get "app" "name")

  options:
     -d                   Target wireless device name.
                          Default: '$(_get "target" "device")'
     -a                   Get only associated bssid.
                          Default: '$(_get "associated" "only")'

     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

# Shows configuration options.
_show_config() {
  local \
    _call_date
  TZ=UTC \
  printf \
    -v \
      _call_date \
    '%(%FT%R%z)T' \
    "${SOURCE_DATE_EPOCH}"
  _msg_info "${app_name} configuration"
  _msg_info "                Call date:   $(_get "_call" "date")"
  _msg_info "            Target device:   $(_get "target" "device")"
  _msg_info "          Associated only:   $(_get "associated" "only")"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'd:acvh?' \
    arg; do
  case \
    "${arg}" in
    d) override_target_device="${OPTARG}" ;;
    a) override_associated_only="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
_show_config
app_opts=(
  "$( \
    _get \
      "target" \
      "device")"
  "$( \
    _get \
      "associated" \
      "only")"
)
_android_bssid_scan \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
